baseURL = "https://simulateher.github.io/new-website/"


[module]
  [module.hugoVersion]
    extended = false
    max = ""
    min = "0.117.0"

[params]
  description = "Digital humanities student and language enthusiast"
  enableMouseTracker = true
  truncationLimit = 150

  [params.assets]
  logo = "img/logo.png"
  favicon32 = "favicon-32x32.png"


  [[params.socialIcons]]
    name = "email"
    url = "mailto:johanna.marthe.israel@gmail.com"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/simulateher"

  [[params.itemDisplays]]
    name = "BA Thesis on Slaughterhouse-Five"
    url = "#"
    description = "A postmodernist analysis of mortality in Vonnegutâ€™s novel."

  [[params.itemDisplays]]
    name = "Publishing Internship"
    url = "#"
    description = "Oversaw translation projects and managed editorial workflows."

  [[params.itemDisplays]]
    name = "Digital Humanities Project"
    url = "#"
    description = "Textual analysis using R in a course on data sustainability."

  customCSS = ["css/main.css"]


